config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/user/:id/sticks" => 'users#sticks', as: "user_sticks"
    get "/user/:id/sticks/:id" => 'users#stick', as: "user_stick"
    get "/user/:id" => 'users#show', as: "user"
  end

  #get "/sticks/:id" => 'sticks#show', as: "stick"

  root to: "home#index"
  
  resources :sticks do 
    resources :reviews
  end

  

=begin   resources :reviews do 
    resources :sticks
  end 
=end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :stick

     validates :review, presence: true
     validates :review, length: { minimum: 5 }
    

    accepts_nested_attributes_for :stick

    #default_scope { order(created_at: :desc)}
    
    scope :newest_first, -> { order(created_at: :desc) }

    # def self.find_by_stick(stick_id)
    #     Review.where(stick_id: stick_id)
    #   end
end

app/models/session.rb
class Session < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/stick.rb
class Stick < ApplicationRecord
    has_many :reviews, dependent: :destroy 
    has_many :users, through: :reviews
    belongs_to :user

    validates :brand, :model, :size, :flex, presence: true

    scope :newest_first, -> { order(created_at: :desc) }
    
    
    accepts_nested_attributes_for :users


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         # <---- LESSON ---->
         # Step Fourteen:
         # Add omniauthable and pass in which ever providers you are using here.
         :omniauthable, omniauth_providers:[:github]



  has_many :reviews
  has_many :sticks, through: :reviews

  accepts_nested_attributes_for :sticks

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_stick
    def current_stick
        #binding.pry
        @current_stick = Stick.find_by(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index 
        if user_signed_in?
            render 'users/show'
        else 
            root_path
        end
    end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

    def github
        @user = User.create_from_provider_data(request.env['omniauth.auth'])

        if @user.persisted?
            sign_in_and_redirect @user
          else
            flash[:error] = 'There was a problem signing you in through Github. Please register or try signing in later.'
            redirect_to new_user_registration_url
      end
    end

    def failure
        flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
        redirect_to new_user_registration_url
      end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   
    def index
       #binding.pry
        @reviews = Review.newest_first
    end

    def show 
        # binding.pry
        @review = Review.find_by(id: params[:id])
    end

    def new
        @review = Review.new
        
        @stick = Stick.find_by(id: params[:stick_id])
        
    end

    def create
        @review = Review.create(review_params)
        if @review.save
            redirect_to stick_path(@review.stick)
        else
            render :new
        end
        #review_params.merge({user_id:current_user.id})
    end

    def edit
        #binding.pry
        @stick = Stick.find_by(id: params[:stick_id])
        @review = Review.find(params[:id])
    end

    def update
        @review = Review.find(params[:id])
        @review.update(review_params)
        if @review.save
            redirect_to stick_review_path
        else
            render :edit
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to sticks_path, notice: "Review deleted!!!"
    end
 
    private 


    def review_params
        params.require(:review).permit(:review, :user_id, :stick_id)
    end
end

app/controllers/sticks_controller.rb
class SticksController < ApplicationController
    
    before_action :authenticate_user!, except: [:index]
   

    def index 
        @sticks = Stick.newest_first
    end    

    def show 
        
        @stick = Stick.find(params[:id])
    end

    def new
        @stick = Stick.new
    end

    def create
        #byebug
            @stick = Stick.new(stick_params)
            if @stick.save
                redirect_to stick_path(@stick)
            else
                render :new
        end
    end
    # (stick_params.merge({:user_id => current_user.id}))
    def edit
        @stick = Stick.find(params[:id])
      
    end

    def update
        binding.pry
        @stick = Stick.find(params[:id])
        if @stick.update(stick_params)
            redirect_to @stick
        else
            render :edit
        end
    end

    def destroy
        binding.pry
        @stick = Stick.find(params[:id])
        @stick.destroy
        redirect_to  user_path(:user_id), notice: "Stick Deleted!!!"      
    end



    private 

    def set_stick
        current_stick = @stick.id
    end

    
    

    def stick_params
        params.require(:stick).permit(:brand, :model, :size, :flex, :user_id)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show 
        @user = User.find_by(id: params[:id])
    end

    def sticks
        @sticks = Stick.where(user_id: current_user.id) 
        render "sticks/index"
    end

    # def stick 
    #     @stick = Stick.find(params[:id])
    #     render "sticks/show"
    # end

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/views/home/index.html.erb
<h1 Welcome to twigs ></h1>

<h2>New to Twigs regiser below!</h2><br>
 
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            

<h3> Already a member sign in below!</h3>
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twig</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<%= form_for [@stick, @review] do |f| %>
  <div class="form-group">

  

  <div class="field"> 
    <h3><%= f.label :review %><br></h3>
    <%= f.text_area :review %>
   </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<% @reviews.each do |review|%><br>

   Brand: <%= review.stick.brand%><br>

    Model: <%= review.stick.model%><br>

    Review By: <%= review.user.email%>- <%= review.review %><br>

    

<% end %>

app/views/reviews/new.html.erb
<h2>Add a Review </h2>




<%= form_for [@stick, @review] do |f| %>
    <p>
    <%binding.pry%>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :stick_id, value: @stick.id %>
      <%= f.label :review %><br>
      <%= f.text_area :review  %>
      
    </p>
    
  
      <%= f.submit %>
    
  <% end %>

  <%= link_to 'Back', sticks_path(@review.stick) %>

app/views/reviews/show.html.erb
<h2>Review:</h2>

<%= @review.user.email %><br>
<%= @review.stick.brand %><br>
<%= @review.review %><br>

<% if @review.user_id == current_user.id %>
 <%= button_to "Delete", stick_review_path(@review),  :method => :delete  %>
 <%= link_to "Edit", edit_stick_review_path(@review.stick, @review)%>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
            
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                <%= link_to 'HomePage', user_path(:user_id), class: 'nav=link'%>
            </li>
        <% else %>
             <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>

             <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>


            <%end%>
        
      </ul>
    </div>
  </div>
</nav>

app/views/sticks/_form.html.erb
<% if @stick.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@stick.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @stick.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>




<%= form_for @stick do |f| %>
    <%= f.label :brand %>
    <div><%= f.text_field :brand %></div>
    <p><%= f.label :model %></p>
    <div><%= f.text_field :model %></div>
    <p><%= f.label :size %></p>
    <div><%= f.text_field :size %></div>
    <p><%= f.label :flex %></p>
    <div><%= f.text_field :flex %></div>
  
     <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.submit "Submit" %>
<% end %>

app/views/sticks/edit.html.erb
<h1>Edit Form</h1>

<%= render 'form'%>

app/views/sticks/index.html.erb
<h2> Sticks </h2><br>




<% @sticks.each do |stick|%><br>
 
    <%= stick.user.email%><br>

    <%= link_to stick.brand, stick_path(stick.id) %><br>

    <%= stick.model %><br>

<% end %>

app/views/sticks/new.html.erb
<h2> Add a Stick </h2>



<%= render 'form'%>

app/views/sticks/show.html.erb
<%= link_to 'Back', sticks_path %><br>

Brand: <%= @stick.brand %><br>
Model: <%= @stick.model %><br>
Size: <%= @stick.size%><br>
Flex: <%= @stick.flex%><br>
User: <%= @stick.user_id%><br>




  <% if @stick.user_id == current_user.id %>
    <%= link_to "Edit",  edit_stick_path(@stick) %><br>
    
    <%= button_to "Delete", stick_path(@stick),  :method => :delete %>
  <% end %>





<div id="stick-review">
    <%= link_to 'Please add a Review', new_stick_review_path(@stick) %>
    <% @stick.reviews.each do |review| %>
      <h3>User: <%=review.user.email%></h3>
      Review: <%=link_to 'Review', stick_review_path(@stick, review) %>
  <% end %>
</div> 

app/views/users/show.html.erb
<h2> twigs </h2>
<%= current_user.email %><br>

<%= link_to 'All Twigs', sticks_path %><br>
<%= link_to 'Your Twigs', user_sticks_path(:user_id) %><br>
<%= link_to 'Log a new twig', new_stick_path(:user_id)%>